import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { getServerSession } from "next-auth";

import AdminHeader from "../../components/AdminHeader";
import { Toaster } from "@/components/ui/toaster";

import { authOptions } from "@/lib/authOptions";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  if (!session) redirect("/login");

  return (
    <div dir="rtl" className=" px-5 pt-12">
      <div className="fixed z-10 top-5 right-5">
        <AdminHeader />
      </div>
      {children}
      <Toaster />
    </div>
  );
}
